## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Introduction to serverless for developers:part3 GitHub to Slack
  
##########################################################################
#  Parameters & Globals                                                  #
##########################################################################
Parameters:
  slackUrl:
    Type: String
    Description: your Slack Webhook Url.
    Default: ""
Resources:
##########################################################################
#   Lambda Functions                                                      #
##########################################################################
  StarWebhookHandler:
    Type: AWS::Serverless::Function
    Description: A github webhook handler when repo is starred
    Properties:
      CodeUri: src_starred/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 3
      Environment:
        Variables:
          slackEndpoint: !Ref slackUrl
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
  
  # ForkWebhookHandler:
  #   Type: AWS::Serverless::Function
  #   Description: A github webhook handler when repo is forked
  #   Properties:
  #     CodeUri: src_forked/
  #     Handler: app.handler
  #     Runtime: nodejs12.x
  #     Timeout: 3
  #     Environment:
  #       Variables:
  #         slackEndpoint: !Ref slackUrl
  #     Events:
  #       HttpApiEvent:
  #         Type: HttpApi
  #         Properties:
  #           Path: /fork
  #           Method: POST


##########################################################################
#   Stack outputs                                                        #
##########################################################################
Outputs:
  StarGitHubEndpoint:
    Description: "The star invocation URl to provide to github webhook"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  ForkGitHubEndpoint:
    Description: "The fork invocation URl to provide to github webhook"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/fork"



